### PR TITLE
fix!: use low-cardinality span name and remove serviceName option

### LINKED ISSUE #40: Use low cardinality span name
[otel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name) recommending to use low cardinality span names 

>HTTP spans MUST follow the overall guidelines for span names. Many REST APIs encode parameters into URI path, e.g. /api/users/123 where 123 is a user id, which creates high cardinality value space not suitable for span names. In case of HTTP servers, these endpoints are often mapped by the server frameworks to more concise HTTP routes, e.g. /api/users/{user_id}, which are recommended as the low cardinality span names

Do you think it's a good choice to `routerPath` from fastify request instead of raw request URL by default when generating span name?
https://github.com/autotelic/fastify-opentelemetry/blob/dd3a6b64f45da36288b331e09f1f681f3160e842/index.js#L13-L15

### PR DESCRIPTION
**Pull request by cvrajeesh**
* Use low-cardinality span name. Use `routerPath` instead of raw URL
* removed service name from the option because span name does not need to contain service name, service name should be set either on the provider or exporter.
    
  ```
  import { ResourceAttributes } from "@opentelemetry/semantic-conventions";
  import { SimpleSpanProcessor } from "@opentelemetry/tracing";
  
  .....
  const traceProvider = new NodeTracerProvider({
    resource: new Resource({
      [ResourceAttributes.SERVICE_NAME]: "myservice",
    }),
  });
  ```
    
**BREAKING CHANGE!**: service name removed from the usage and formatSpanName

Closes #40

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -10,8 +10,12 @@ const {
...
 const { name: moduleName, version: moduleVersion } = require('./package.json')
 
-function defaultFormatSpanName (serviceName, rawReq) {
-  return `${serviceName} - ${rawReq.method} - ${rawReq.url}`
+function defaultFormatSpanName (request) {
+  const parts = [request.method]
+  if(request.routerPath) {
+    parts.push(request.routerPath)
+  }
+  return parts.join(" ")
```
Comment (HW13) [inline index.js:18]: Could we simplify this into a ternary?

```suggestion
const { method, routerPath } = request
return routerPath ? `${method} ${routerPath}` : method
```

**Review by HW13 — CHANGES_REQUESTED** [review]
Thanks for the contribution @cvrajeesh!

This is looking good, just a couple requests:

- The validation workflow is failing due to lint errors, could we fix those?
- Could we update the README?

File: index.js (hunk 1 above)
Comment (cvrajeesh) [reply index.js]: Fixed :)

**Comment by cvrajeesh** [comment]
@HW13 I've made the changes please review

**Comment by cvrajeesh** [comment]
@HW13 did you get a chance to review the latest changes?

**Review by HW13 — APPROVED** [review]
LGTM. Thanks @cvrajeesh! 😎 👍
